document.addEventListener('DOMContentLoaded', function () {

  // ─── STATE ───────────────────────────────────────────────────────────────────
  let isAnnualBilling = false;
  let currentPage = 'home';
  let currentDoc = 'getting-started';
  let currentBlogFilter = 'all';
  let mobileMenuOpen = false;
  let buildLogInterval = null;
  let typewriterInterval = null;
  let isLoggedIn = !!localStorage.getItem('token');

  const DEMO_PROMPTS = [
    'A task manager with Kanban board and user auth',
    'A SaaS dashboard with Stripe billing and analytics',
    'A blog platform with markdown editor and comments',
    'A real-time chat app with rooms and file uploads',
  ];

  const BUILDS_DATA = [
    { id: 1, name: 'TaskFlow Pro', status: 'live', framework: 'Next.js', built: '2 hours ago', url: 'https://taskflow.buildorbit.app' },
    { id: 2, name: 'SaaS Dashboard', status: 'live', framework: 'React', built: '1 day ago', url: 'https://saas-dash.buildorbit.app' },
    { id: 3, name: 'Blog Engine', status: 'building', framework: 'Next.js', built: '2 days ago', url: null },
    { id: 4, name: 'Chat App', status: 'live', framework: 'Express', built: '3 days ago', url: 'https://chat.buildorbit.app' },
    { id: 5, name: 'Portfolio Site', status: 'failed', framework: 'React', built: '5 days ago', url: null },
    { id: 6, name: 'E-commerce Store', status: 'live', framework: 'Next.js', built: '1 week ago', url: 'https://store.buildorbit.app' },
    { id: 7, name: 'Analytics Tool', status: 'live', framework: 'React', built: '2 weeks ago', url: 'https://analytics.buildorbit.app' },
  ];

  const BLOG_POSTS = [
    { id: 1, category: 'tutorial', title: 'Build a SaaS MVP in One Afternoon', excerpt: 'Step-by-step guide to shipping a full-stack SaaS with auth, billing, and a dashboard using BuildOrbit.', date: 'Jan 15, 2025', readTime: '8 min read', emoji: '🚀' },
    { id: 2, category: 'update', title: 'BuildOrbit v2.0: Full-Stack Support', excerpt: 'We\'re excited to announce full-stack app generation with database, auth, and API routes — all in one prompt.', date: 'Jan 10, 2025', readTime: '4 min read', emoji: '🎉' },
    { id: 3, category: 'engineering', title: 'How We Achieve 8-Second Build Times', excerpt: 'A deep dive into our build pipeline, caching strategies, and the infrastructure that makes instant deploys possible.', date: 'Jan 5, 2025', readTime: '12 min read', emoji: '⚡' },
    { id: 4, category: 'tutorial', title: 'Adding Stripe Payments to Your BuildOrbit App', excerpt: 'Learn how to integrate Stripe subscriptions and one-time payments into any app generated by BuildOrbit.', date: 'Dec 28, 2024', readTime: '10 min read', emoji: '💳' },
    { id: 5, category: 'engineering', title: 'Our AI Code Generation Architecture', excerpt: 'How we fine-tuned our models to produce clean, production-quality code instead of prototype-quality garbage.', date: 'Dec 20, 2024', readTime: '15 min read', emoji: '🤖' },
    { id: 6, category: 'update', title: 'Custom Domains Are Now Available', excerpt: 'Connect your own domain to any BuildOrbit deployment in under 60 seconds. No DNS expertise required.', date: 'Dec 15, 2024', readTime: '3 min read', emoji: '🌐' },
  ];

  const DOCS_CONTENT = {
    'getting-started': {
      title: 'Getting Started',
      content: `
        <h2 class="text-2xl font-bold text-gray-900 mb-4">Getting Started with BuildOrbit</h2>
        <p class="text-gray-600 mb-6">Welcome to BuildOrbit! This guide will walk you through creating and deploying your first app in under 5 minutes.</p>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Prerequisites</h3>
        <ul class="list-disc list-inside text-gray-600 space-y-2 mb-6">
          <li>A BuildOrbit account (free to create)</li>
          <li>A modern web browser</li>
          <li>An idea for an app (or use one of our templates)</li>
        </ul>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Step 1: Create Your Account</h3>
        <p class="text-gray-600 mb-4">Click "Get Started Free" in the top navigation. No credit card required for the Starter plan.</p>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Step 2: Describe Your App</h3>
        <p class="text-gray-600 mb-4">In the Builder, type a description of what you want to build. Be as specific or as vague as you like — our AI handles the details.</p>
        <div class="bg-gray-900 rounded-lg p-4 mb-6">
          <p class="text-green-400 font-mono text-sm">Example: "A task manager with user authentication, a Kanban board, and email notifications"</p>
        </div>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Step 3: Hit Build</h3>
        <p class="text-gray-600 mb-4">Click the "Build It" button and watch your app come to life. In about 8 seconds, you'll have a live URL to share.</p>
        <div class="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <p class="text-blue-800 text-sm font-medium">💡 Pro Tip: The more specific your prompt, the better the output. Include details about the tech stack, features, and design style you want.</p>
        </div>
      `
    },
    'builder': {
      title: 'Builder Guide',
      content: `
        <h2 class="text-2xl font-bold text-gray-900 mb-4">Builder Guide</h2>
        <p class="text-gray-600 mb-6">The BuildOrbit Builder is your primary interface for creating apps. Here's everything you need to know.</p>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Writing Effective Prompts</h3>
        <p class="text-gray-600 mb-4">The quality of your prompt directly affects the quality of the generated app. Here are some tips:</p>
        <ul class="list-disc list-inside text-gray-600 space-y-2 mb-6">
          <li>Specify the tech stack (React, Next.js, Express, etc.)</li>
          <li>List the key features you need</li>
          <li>Mention authentication requirements</li>
          <li>Describe the data model if you have one in mind</li>
          <li>Include design preferences (minimal, colorful, dark mode, etc.)</li>
        </ul>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Supported Frameworks</h3>
        <div class="grid grid-cols-2 gap-3 mb-6">
          <div class="bg-gray-50 rounded-lg p-3 text-sm font-medium text-gray-700">⚛️ React</div>
          <div class="bg-gray-50 rounded-lg p-3 text-sm font-medium text-gray-700">▲ Next.js</div>
          <div class="bg-gray-50 rounded-lg p-3 text-sm font-medium text-gray-700">🟢 Node/Express</div>
          <div class="bg-gray-50 rounded-lg p-3 text-sm font-medium text-gray-700">🔷 TypeScript</div>
        </div>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Iterating on Your Build</h3>
        <p class="text-gray-600">After your first build, you can refine it by providing follow-up prompts. Each iteration creates a new deployment while keeping your history intact.</p>
      `
    },
    'deployments': {
      title: 'Deployments',
      content: `
        <h2 class="text-2xl font-bold text-gray-900 mb-4">Deployments</h2>
        <p class="text-gray-600 mb-6">Every build automatically creates a deployment. Here's how deployments work in BuildOrbit.</p>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Automatic Deployments</h3>
        <p class="text-gray-600 mb-4">When you click "Build It", BuildOrbit automatically:</p>
        <ol class="list-decimal list-inside text-gray-600 space-y-2 mb-6">
          <li>Generates your application code</li>
          <li>Runs automated tests</li>
          <li>Builds the production bundle</li>
          <li>Deploys to our global CDN</li>
          <li>Provides you with a live URL</li>
        </ol>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Custom Domains</h3>
        <p class="text-gray-600 mb-4">Pro and Team plans support custom domains. Add your domain in the deployment settings and follow the DNS instructions.</p>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Environment Variables</h3>
        <div class="bg-gray-900 rounded-lg p-4 mb-4">
          <p class="text-gray-400 font-mono text-xs">DATABASE_URL=postgresql://...</p>
          <p class="text-gray-400 font-mono text-xs">STRIPE_SECRET_KEY=sk_live_...</p>
          <p class="text-gray-400 font-mono text-xs">NEXTAUTH_SECRET=your-secret</p>
        </div>
        <p class="text-gray-600">Set environment variables in your deployment settings. They're encrypted at rest and never exposed in build logs.</p>
      `
    },
    'api': {
      title: 'API Reference',
      content: `
        <h2 class="text-2xl font-bold text-gray-900 mb-4">API Reference</h2>
        <p class="text-gray-600 mb-6">The BuildOrbit API lets you trigger builds, manage deployments, and retrieve logs programmatically.</p>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Authentication</h3>
        <p class="text-gray-600 mb-4">All API requests require a Bearer token in the Authorization header:</p>
        <div class="bg-gray-900 rounded-lg p-4 mb-6">
          <p class="text-green-400 font-mono text-sm">Authorization: Bearer YOUR_API_KEY</p>
        </div>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">Endpoints</h3>
        <div class="space-y-4">
          <div class="border border-gray-200 rounded-lg p-4">
            <div class="flex items-center gap-2 mb-2">
              <span class="bg-green-100 text-green-700 text-xs font-bold px-2 py-0.5 rounded">POST</span>
              <code class="text-sm font-mono text-gray-700">/api/builds</code>
            </div>
            <p class="text-gray-600 text-sm">Trigger a new build with a prompt.</p>
          </div>
          <div class="border border-gray-200 rounded-lg p-4">
            <div class="flex items-center gap-2 mb-2">
              <span class="bg-blue-100 text-blue-700 text-xs font-bold px-2 py-0.5 rounded">GET</span>
              <code class="text-sm font-mono text-gray-700">/api/builds/:id</code>
            </div>
            <p class="text-gray-600 text-sm">Get build status and details.</p>
          </div>
          <div class="border border-gray-200 rounded-lg p-4">
            <div class="flex items-center gap-2 mb-2">
              <span class="bg-blue-100 text-blue-700 text-xs font-bold px-2 py-0.5 rounded">GET</span>
              <code class="text-sm font-mono text-gray-700">/api/deployments</code>
            </div>
            <p class="text-gray-600 text-sm">List all deployments for your account.</p>
          </div>
          <div class="border border-gray-200 rounded-lg p-4">
            <div class="flex items-center gap-2 mb-2">
              <span class="bg-red-100 text-red-700 text-xs font-bold px-2 py-0.5 rounded">DELETE</span>
              <code class="text-sm font-mono text-gray-700">/api/deployments/:id</code>
            </div>
            <p class="text-gray-600 text-sm">Delete a deployment.</p>
          </div>
        </div>
      `
    },
    'faq': {
      title: 'FAQ',
      content: `
        <h2 class="text-2xl font-bold text-gray-900 mb-4">Frequently Asked Questions</h2>
        <div class="space-y-6">
          <div>
            <h3 class="text-base font-semibold text-gray-900 mb-2">Is the generated code production-ready?</h3>
            <p class="text-gray-600 text-sm">Yes. BuildOrbit generates clean, well-structured code following industry best practices. It includes error handling, input validation, and security measures. You can export and review the code at any time.</p>
          </div>
          <div>
            <h3 class="text-base font-semibold text-gray-900 mb-2">Can I export my code?</h3>
            <p class="text-gray-600 text-sm">Absolutely. Pro and Team plans include full source code export. You own your code — no lock-in. Deploy it anywhere: Vercel, Railway, AWS, or your own server.</p>
          </div>
          <div>
            <h3 class="text-base font-semibold text-gray-900 mb-2">What databases are supported?</h3>
            <p class="text-gray-600 text-sm">BuildOrbit supports PostgreSQL, MySQL, SQLite, and MongoDB. We automatically provision and configure the database for your app.</p>
          </div>
          <div>
            <h3 class="text-base font-semibold text-gray-900 mb-2">How does billing work?</h3>
            <p class="text-gray-600 text-sm">Starter is free forever. Pro is $29/month (or $23/month billed annually). Team is $79/month (or $63/month billed annually). You can upgrade, downgrade, or cancel at any time.</p>
          </div>
          <div>
            <h3 class="text-base font-semibold text-gray-900 mb-2">Is there a free trial for Pro?</h3>
            <p class="text-gray-600 text-sm">Yes! Pro comes with a 14-day free trial. No credit card required to start.</p>
          </div>
          <div>
            <h3 class="text-base font-semibold text-gray-900 mb-2">What kind of support do you offer?</h3>
            <p class="text-gray-600 text-sm">Starter gets community support via our Discord. Pro gets priority email support with a 24-hour response time. Team gets dedicated Slack support with a 4-hour SLA.</p>
          </div>
        </div>
      `
    }
  };

  // ─── UTILITY FUNCTIONS ───────────────────────────────────────────────────────

  function showToast(message, type = 'info') {
    const existing = document.getElementById('toast-notification');
    if (existing) existing.remove();

    const colors = {
      info: 'bg-gray-900 text-white',
      success: 'bg-green-600 text-white',
      error: 'bg-red-600 text-white',
      warning: 'bg-yellow-500 text-white'
    };

    const toast = document.createElement('div');
    toast.id = 'toast-notification';
    toast.className = `fixed bottom-6 right-6 z-[9999] px-5 py-3 rounded-xl shadow-xl text-sm font-medium transition-all duration-300 ${colors[type] || colors.info}`;
    toast.textContent = message;
    document.body.appendChild(toast);

    setTimeout(() => {
      toast.style.opacity = '0';
      toast.style.transform = 'translateY(10px)';
      setTimeout(() => toast.remove(), 300);
    }, 3500);
  }

  function showModal(title, bodyHTML, onConfirm) {
    const existing = document.getElementById('app-modal');
    if (existing) existing.remove();

    const modal = document.createElement('div');
    modal.id = 'app-modal';
    modal.className = 'fixed inset-0 z-[9998] flex items-center justify-center bg-black bg-opacity-50 px-4';
    modal.innerHTML = `
      <div class="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6 animate-slide-up">
        <h3 class="text-lg font-bold text-gray-900 mb-3">${title}</h3>
        <div class="text-gray-600 text-sm mb-6">${bodyHTML}</div>
        <div class="flex gap-3 justify-end">
          <button id="modal-cancel" class="px-4 py-2 text-sm font-medium text-gray-600 hover:bg-gray-100 rounded-lg transition-colors">Cancel</button>
          ${onConfirm ? '<button id="modal-confirm" class="px-4 py-2 text-sm font-medium bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors">Confirm</button>' : ''}
        </div>
      </div>
    `;
    document.body.appendChild(modal);

    document.getElementById('modal-cancel').addEventListener('click', () => modal.remove());
    modal.addEventListener('click', (e) => { if (e.target === modal) modal.remove(); });
    if (onConfirm) {
      document.getElementById('modal-confirm').addEventListener('click', () => {
        onConfirm();
        modal.remove();
      });
    }
  }

  function setButtonLoading(btn, loading, originalText) {
    if (loading) {
      btn.disabled = true;
      btn.dataset.originalText = btn.textContent;
      btn.textContent = 'Loading...';
      btn.classList.add('opacity-75', 'cursor-not-allowed');
    } else {
      btn.disabled = false;
      btn.textContent = originalText || btn.dataset.originalText || btn.textContent;
      btn.classList.remove('opacity-75', 'cursor-not-allowed');
    }
  }

  // ─── PAGE NAVIGATION ─────────────────────────────────────────────────────────

  function showPage(pageId) {
    document.querySelectorAll('.page-view').forEach(p => p.classList.add('hidden'));
    const target = document.getElementById('page-' + pageId);
    if (target) {
      target.classList.remove('hidden');
      currentPage = pageId;
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }

    // Update nav active state
    document.querySelectorAll('.nav-link').forEach(btn => {
      btn.classList.remove('text-blue-600', 'bg-blue-50');
      if (btn.dataset.section === pageId) {
        btn.classList.add('text-blue-600', 'bg-blue-50');
      }
    });

    // Close mobile menu
    closeMobileMenu();

    // Page-specific init
    if (pageId === 'blog') renderBlogPosts(currentBlogFilter);
    if (pageId === 'docs') renderDocContent(currentDoc);
    if (pageId === 'dashboard') {
      if (!isLoggedIn) {
        showPage('auth');
        showToast('Please log in to access your dashboard.', 'warning');
        return;
      }
      renderBuildsTable(BUILDS_DATA);
    }
  }

  function scrollToSection(sectionId) {
    if (currentPage !== 'home') {
      showPage('home');
      setTimeout(() => {
        const el = document.getElementById('section-' + sectionId);
        if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 100);
    } else {
      const el = document.getElementById('section-' + sectionId);
      if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
    closeMobileMenu();
  }

  // ─── MOBILE MENU ─────────────────────────────────────────────────────────────

  function closeMobileMenu() {
    const menu = document.getElementById('mobile-menu');
    const hamburger = document.getElementById('hamburger-icon');
    const closeIcon = document.getElementById('close-icon');
    menu.classList.add('hidden');
    hamburger.classList.remove('hidden');
    closeIcon.classList.add('hidden');
    mobileMenuOpen = false;
  }

  document.getElementById('mobile-menu-btn').addEventListener('click', function () {
    const menu = document.getElementById('mobile-menu');
    const hamburger = document.getElementById('hamburger-icon');
    const closeIcon = document.getElementById('close-icon');
    mobileMenuOpen = !mobileMenuOpen;
    menu.classList.toggle('hidden', !mobileMenuOpen);
    hamburger.classList.toggle('hidden', mobileMenuOpen);
    closeIcon.classList.toggle('hidden', !mobileMenuOpen);
  });

  // ─── NAV LINKS ───────────────────────────────────────────────────────────────

  document.querySelectorAll('.nav-link').forEach(btn => {
    btn.addEventListener('click', function () {
      const section = this.dataset.section;
      if (['features', 'how-it-works', 'pricing'].includes(section)) {
        scrollToSection(section);
      } else if (section === 'blog') {
        showPage('blog');
      } else if (section === 'docs') {
        showPage('docs');
      }
    });
  });

  // ─── NAVBAR LOGO ─────────────────────────────────────────────────────────────

  document.getElementById('nav-logo').addEventListener('click', function () {
    showPage('home');
  });

  // ─── AUTH BUTTONS ─────────────────────────────────────────────────────────────

  document.getElementById('nav-login-btn').addEventListener('click', function () {
    showAuthPage('login');
  });

  document.getElementById('nav-signup-btn').addEventListener('click', function () {
    showAuthPage('signup');
  });

  document.getElementById('mobile-login-btn').addEventListener('click', function () {
    showAuthPage('login');
  });

  document.getElementById('mobile-signup-btn').addEventListener('click', function () {
    showAuthPage('signup');
  });

  function showAuthPage(tab) {
    showPage('auth');
    if (tab === 'signup') {
      switchAuthTab('signup');
    } else {
      switchAuthTab('login');
    }
  }

  function switchAuthTab(tab) {
    const loginTab = document.getElementById('auth-login-tab');
    const signupTab = document.getElementById('auth-signup-tab');
    const loginForm = document.getElementById('auth-login-form');
    const signupForm = document.getElementById('auth-signup-form');

    if (tab === 'login') {
      loginTab.classList.add('bg-white', 'text-gray-900', 'shadow-sm');
      loginTab.classList.remove('text-gray-500');
      signupTab.classList.remove('bg-white', 'text-gray-900', 'shadow-sm');
      signupTab.classList.add('text-gray-500');
      loginForm.classList.remove('hidden');
      signupForm.classList.add('hidden');
    } else {
      signupTab.classList.add('bg-white', 'text-gray-900', 'shadow-sm');
      signupTab.classList.remove('text-gray-500');
      loginTab.classList.remove('bg-white', 'text-gray-900', 'shadow-sm');
      loginTab.classList.add('text-gray-500');
      signupForm.classList.remove('hidden');
      loginForm.classList.add('hidden');
    }
  }

  // ─── HERO BUTTONS ────────────────────────────────────────────────────────────

  document.getElementById('hero-cta-btn').addEventListener('click', function () {
    showAuthPage('signup');
  });

  document.getElementById('hero-demo-btn').addEventListener('click', function () {
    showModal(
      '▶ Watch Demo',
      `<div class="bg-gray-900 rounded-xl aspect-video flex items-center justify-center">
        <div class="text-center">
          <div class="text-5xl mb-3">🎬</div>
          <p class="text-white font-medium">Demo Video</p>
          <p class="text-gray-400 text-xs mt-1">Coming soon — sign up for early access</p>
        </div>
      </div>
      <p class="mt-4 text-center">Want to see BuildOrbit in action? <strong>Sign up free</strong> and try it yourself in seconds.</p>`,
      null
    );
    // Add a "Sign Up" button to the modal after it's created
    setTimeout(() => {
      const modal = document.getElementById('app-modal');
      if (modal) {
        const cancelBtn = modal.querySelector('#modal-cancel');
        if (cancelBtn) {
          cancelBtn.textContent = 'Close';
          const signupBtn = document.createElement('button');
          signupBtn.className = 'px-4 py-2 text-sm font-medium bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors';
          signupBtn.textContent = 'Sign Up Free';
          signupBtn.addEventListener('click', () => {
            modal.remove();
            showAuthPage('signup');
          });
          cancelBtn.parentNode.appendChild(signupBtn);
        }
      }
    }, 10);
  });

  // ─── DEMO BUILDER ────────────────────────────────────────────────────────────

  let currentPromptIndex = 0;
  let currentCharIndex = 0;
  let isTyping = false;

  function startTypewriter() {
    const el = document.getElementById('demo-prompt-text');
    if (!el) return;
    if (typewriterInterval) clearInterval(typewriterInterval);

    const prompt = DEMO_PROMPTS[currentPromptIndex % DEMO_PROMPTS.length];
    el.textContent = '';
    currentCharIndex = 0;
    isTyping = true;

    typewriterInterval = setInterval(() => {
      if (currentCharIndex < prompt.length) {
        el.textContent += prompt[currentCharIndex];
        currentCharIndex++;
      } else {
        clearInterval(typewriterInterval);
        isTyping = false;
        setTimeout(() => {
          currentPromptIndex++;
          startTypewriter();
        }, 3000);
      }
    }, 50);
  }

  startTypewriter();

  document.getElementById('demo-build-btn').addEventListener('click', function () {
    const promptEl = document.getElementById('demo-prompt-text');
    const prompt = promptEl ? promptEl.textContent.trim() : '';

    if (!prompt) {
      showToast('Please wait for the prompt to finish typing, or clear and type your own.', 'warning');
      return;
    }

    runDemoBuild(prompt);
  });

  document.getElementById('demo-clear-btn').addEventListener('click', function () {
    const el = document.getElementById('demo-prompt-text');
    if (el) el.textContent = '';
    if (typewriterInterval) clearInterval(typewriterInterval);
    isTyping = false;

    const buildLog = document.getElementById('build-log');
    if (buildLog) {
      buildLog.innerHTML = '<p class="text-gray-500">Waiting for build...</p>';
    }
    if (buildLogInterval) clearInterval(buildLogInterval);

    // Make prompt editable
    if (el) {
      el.contentEditable = 'true';
      el.focus();
      el.setAttribute('placeholder', 'Type your app description here...');
    }
  });

  function runDemoBuild(prompt) {
    const buildLog = document.getElementById('build-log');
    if (!buildLog) return;

    if (buildLogInterval) clearInterval(buildLogInterval);

    const steps = [
      { text: '> Analyzing prompt...', color: 'text-blue-400', delay: 0 },
      { text: '> Selecting tech stack: Next.js + PostgreSQL', color: 'text-gray-300', delay: 600 },
      { text: '> Generating project structure...', color: 'text-gray-300', delay: 1200 },
      { text: '> Writing components (12 files)', color: 'text-gray-300', delay: 1800 },
      { text: '> Setting up authentication...', color: 'text-gray-300', delay: 2400 },
      { text: '> Configuring database schema...', color: 'text-gray-300', delay: 3000 },
      { text: '> Running tests... ✓ 24/24 passed', color: 'text-green-400', delay: 3800 },
      { text: '> Building production bundle...',